### PR TITLE
modified write_fits to fix error with local save

### PR DESCRIPTION
**Pull request by parfa30**
There was an error with saving to a local file on the TTS. Not sure if this is related to what is happening at the summit as well.

### CODE REVIEW

**Comment by parfa30** [comment]
I still have the problem with writing local files at the TTS. Not sure if the OBSID solution will fix it?

**Comment by tribeiro** [comment]
I did noticed that the names we are publishing to the LFA are not right though. I think one patch we need to make is [here](https://github.com/lsst-ts/ts_electrometer/blob/994d9440f01c9edba3156624cac329ec284ef3f6/python/lsst/ts/electrometer/controller.py#L530), such that it uses the name provided by the name server. 

I think it should be something like:

```
                f"{self.csc.bucket.name}/{filename}"
```

**Comment by tribeiro** [comment]
You could also add a failover condition to make sure we preserve the file in case of issues [here](https://github.com/lsst-ts/ts_electrometer/blob/994d9440f01c9edba3156624cac329ec284ef3f6/python/lsst/ts/electrometer/controller.py#L513).

Something like:

```
        try:
            pathlib.Path(self.file_output_dir).mkdir(parents=True, exist_ok=True)
            hdul.writeto(f"{self.file_output_dir}/{filename}")
            self.log.info(
                f"Electrometer Scan data file written: {filename}\n"
                f"Scan Summary of Signal [Mean, median, std] is: "
                f"[{np.mean(signal):0.5e}, {np.median(signal):0.5e}, {np.std(signal):0.5e}]\n"
                f"Scan Summary of Time [Mean, median] is: "
                f"[{np.mean(times):0.5e}, {np.median(times):0.5e}]"
            )
        except Exception as e:
            filename += "".join(random.choices(string.ascii_uppercase + string.digits + string.ascii_lowercase, k=7))
            msg = f"Failed to write {filename} to local disk. "
            self.log.exception(msg)
            raise RuntimeError(e)
```

you will need to import random and string for the above to work.

**Comment by parfa30** [comment]
Issue was with naming service

**Pull request closed without merging**
